### ISSUE TITLE
[Bug] Content-Type: application/json isn't working as expected

### ISSUE THREAD

**Issue by m7vm7v** [prateekkathal/laravel-simplecurl#2] opened 2017-01-16 14:52 UTC
Hi, when I try to see the content-type:

`dd($response->getResponseContentType());`

the returned value is always false even when I have :

```
$headers = [
            'Content-Type: application/json',
            'Accept: application/json',
        ];
```

```
$response = new SimpleCurl();
$response->post($url, $inputs, $headers);
```

if i only

`dd($response);`

I got also:

`"content_type" => false`

Thanks for your time.

**Comment by prateekkathal** [comment] 2017-01-16 15:13
Hi @m7vm7v 

Can you tell me what is the output of 

    $simpleCurl->post(...)->getCurlResult();

Waiting :)

**Comment by m7vm7v** [comment] 2017-01-16 15:55
```
array:10 [
  "http_code" => 400
  "request_size" => 310
  "curl_error" => ""
  "url" => "url"
  "content_type" => false
  "redirect_count" => 0
  "effective_url" => "url"
  "total_time" => 0.719
  "result" => "Unable to parse context in body"
  "status" => "failed"
]
```

**Comment by prateekkathal** [comment] 2017-01-16 16:52
It seems the result you are getting after hitting your api is not of the type `application/json`. It seems to be of the type `text/html` to me ... since you are getting the error **Unable to parse context in body**. Also, what are you sending as inputs? Is it an array?

I just tested the code on a working api in my local machine and the content type returned is correct in that case.

Here is the output I got from that API. 

    array:10 [▼
      "http_code" => 200
      "request_size" => 243
      "curl_error" => ""
      "url" => "http://localhost/myproject/public/api/v1/users/1"
      "content_type" => "application/json"
      "redirect_count" => 0
      "effective_url" => "http://localhost/myproject/public/api/v1/users/1"
      "total_time" => 0.308272
      "result" => "{"data":{"id":1,"name":"Prateek Kathal","gender":"Male"}}"
      "status" => "success"
    ]

My headers were the same as yours...

If you can send me a sample code of yours, that'll be great. I won't be able to debug this until then... :)

**Comment by m7vm7v** [comment] 2017-01-16 17:01
Alright. Let me explain all of it.

I am trying to use wit.ai and the pure curl I need to work with is:

```
        curl -XPOST 'https://api.wit.ai/converse?v=20160526&session_id=123abc&q=Bonjour' \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -H 'Authorization: Bearer token
```

'Translated' with this Pack a have :

```
$url = 'https://api.wit.ai/converse';
        $headers = [
            'Content-Type: application/json',
            'Accept: application/json',
            'Authorization: Bearer token',
        ];
        $inputs = [
            'v'            => '20160526',
            'session_id'   => '123abc',
            'q'            => 'Bonjour',
$response = new SimpleCurl();
        $response->post($url, $inputs, $headers);
dd($response->getResponseContentType());
```

**Comment by prateekkathal** [comment] 2017-01-16 17:13
Since I don't have the Bearer token with myself, I tried hitting the api myself on the url you just provided.

My code

    $client = $this->simpleCurl->post('https://api.wit.ai/converse?v=20160526&session_id=123abc', [], [
      'Content-Type: application/json', 'Accept: application/json'
    ]);

    dd($client->getCurlResult(), $client->getResponseContentType());

This is what I got -> 

    array:10 [▼
      "http_code" => 404
      "request_size" => 191
      "curl_error" => ""
      "url" => "https://api.wit.ai/converse?v=20160526&session_id=123abc"
      "content_type" => "application/json"
      "redirect_count" => 0
      "effective_url" => "https://api.wit.ai/converse?v=20160526&session_id=123abc"
      "total_time" => 2.305885
      "result" => "{"body":"wit the hell?"}"
      "status" => "failed"
    ]

    "application/json"

Can you perform `composer update prateekkathal/laravel-simplecurl` from your end once? Even though I haven't changed much from that part, I'd still recommend working on the latest build. 

If you can provide me a token for temporarily, I'll help you debug if the problem is from my end of Api's. 

Let me know :)

**Comment by m7vm7v** [comment] 2017-01-16 17:25
Ok. Thanks ... 
It appears that the inputs are wrong :

```
$inputs = [
            'v'            => '20160526',
            'session_id'   => '123abc',
            'q'            => 'Bonjour',]
```

Without the inputs it is working but I need to send the request with them, 
What is the proper way to send the request with this inputs becouse if I send them in the url like so:

`$url = 'https://api.wit.ai/converse?v=20160526&session_id=123abc&q=Bonjour';`

It does not work. Any ideas about that.

Thanks for your time.

**Comment by prateekkathal** [comment] 2017-01-16 17:47
According to what I can read [here](https://wit.ai/docs/http/20160526#post--converse-link), it seems the correct way of hitting the api is. 

    $url = 'https://api.wit.ai/converse?v=20160526&session_id=123abc&q=' . urlencode('Bonjour');

    $client = $simpleCurl->post($url, [], [
      'Content-Type: application/json',
      'Accept: application/json',
      'Authorization: Bearer token'
    ]);

    // And then finally, get your response by...
    dd($client->getResponseAsArray());

The `context` is the only thing which must be sent as inputs (the second parameter in the above post() function).

I haven't worked on wit.ai's API yet, but I really won't be able to help you get the expected output until I have a **valid session Id** and **token** to get into the api temporarily.

**Comment by m7vm7v** [comment] 2017-01-16 17:51
can i have your email or skype so i ca send you the needed information. thanks

**Comment by prateekkathal** [comment] 2017-01-16 17:57
You can send me a mail on **prateek.kathal.aof@gmail.com**

**Comment by prateekkathal** [comment] 2017-01-16 19:48
Ok. As per our conversation in the email and some testing, I found out there was a very small bug in the `request()` function. I have fixed that and updated the package. Please do this on your end once. (Your package should be updated to **v0.2.3**)

    composer update prateekkathal/laravel-simplecurl

Now, what this is how you can simply send your data.

    $url = 'https://api.wit.ai/converse?v=20160526&session_id=123abc&q=weather%20in%20Brussels';

    $simpleCurl = SimpleCurl::setConfig([
      'defaultHeaders' => [
        'Content-Type: application/json',
        'Accept: application/json',
        'Authorization: Bearer Token',
      ],
    ]);

    $response = $simpleCurl->post($url, json_encode([
      'context' => ['loc' => 'Brussels'],
    ]));

    // And then finally, get your response by...
    dd($response->getResponseAsArray());

Let me know if it working fine for you now. I will mark this issue as closed. 😄 

### Edit
As per my discussion with @m7vm7v, everything is working smoothly now 👍 So... Closing the issue.

**Closed as completed** 2017-01-16 21:01 UTC
